[tool.ruff]
line-length = 125
exclude = [".venv", "venv"]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
testpaths = ["tests"]
log_file = "logs/pytest.log"
log_file_level = "DEBUG"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "sgnlol-slack"
version = "0.1.0"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools]
py-modules = ["app"]

[tool.setuptools.packages.find]
include = ["listeners*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
